---
title: "hw2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Intermediate R

##Relational Operators
#### The greater string is determined based on alphabetical order
#### TRUE == 1, FALSE == 0

#### The && and || operators returns the first element's logic output. 

#### The parenthesis of the for and the while loop is quite different from python. 

#### The V2 looping is new to e. Utilising ':' in R is still very new for myself. 

#### Knowing how to properly use the break and next statements.

#### ?(function) will allow us to get help about functions

#### ... ellipsis is a way for R to pass arguments along without the fucntion having to name them explicitly. 

#### writing a function in R is also totally different from python. Setting default values to arguments are important to prevent running into an error. 

#### The passing arguments by values part, I am still uncertain. Need to relook again. 

#### using lapply to quickly pass list or vector through functions. Both built-in and your own functions. 
* Can return R objects of different classes
* Always store contents in a list.
* Can sometimes repeat homogeneous contents. 

#### sapply function
*Automatically simplify the output from a list to a vector
* but still returns a list if it cannot find a meaningful way to simplify the vector.

#### vapply function
* apply function over list or vector and specify the output. 